# This file is used to generate config.arch, which would be used to
# control archiving of model output.  The scripts and code for
# archiving are not provided in this release, so this config file is
# ignored.

config_arch:
  filename: config.arch
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.arch ##########
    # Archive specific
    
    echo "BEGIN: config.arch"
    
    # Get task specific resources
    . $EXPDIR/config.resources arch
    
    #--online archive of nemsio files for fit2obs verification
    export FITSARC="{tools.YES_NO(doc.archiving.copy_fit2obs_files)}"
    export FHMAX_FITS=132
    if [ $FHMAX_FITS -gt $FHMAX_GFS ]; then export FHMAX_FITS=$FHMAX_GFS; fi
    
    #--starting and ending hours of previous cycles to be removed from rotating directory
    export RMOLDSTD={doc.archiving.scrub_in_archive_start}
    export RMOLDEND={doc.archiving.scrub_in_archive_end}

    export DELETE_COM_IN_ARCHIVE_JOB={tools.YES_NO(doc.archiving.scrub_in_archive)}
    
    echo "END: config.arch"
