config_arch:
  filename: config.arch
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.arch ##########
    # Archive specific
    
    echo "BEGIN: config.arch"
    
    # Get task specific resources
    . $EXPDIR/config.resources arch
    
    #--save data to HPSS archive                               
    export HPSSARCH={tools.YES_NO(doc.output.archive_to_hpss)}
    
    #--online archive of nemsio files for fit2obs verification
    export FITSARC={tools.YES_NO(doc.output.copy_fit2obs_files)}
    
    #--starting and ending hours of previous cycles to be removed from rotating directory
    export RMOLDSTD={doc.output.scrub_in_archive_start}
    #144
    export RMOLDEND={doc.output.scrub_in_archive_end}
    
    
    echo "END: config.arch"
