config_ecen:
  filename: config.ecen
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.ecen ##########
    # Ensemble recentering specific
    
    echo "BEGIN: config.ecen"
    
    # Get task specific resources
    . $EXPDIR/config.resources ecen
    
    export ENKFRECENSH="$HOMEgsi/scripts/exglobal_enkf_recenter_fv3gfs.sh.ecf"
    export nth_ecen={sched.nodes.omp_threads_for(resources.run_ecen)}
    
    export CHGRESEXEC="$HOMEgfs/exec/chgres_recenter.exe"
    export nth_chgres={sched.nodes.omp_threads_for(doc.resources.run_chgres)}
    
    echo "END: config.ecen"
    
