# This file is used to generate config.fax, which has settings for the GFS fax step

config_fax:
  filename: config.fax
  content: !expand |
    #!/bin/ksh -x
   
    ########## config.fax ##########
    # GFS fax step specific

    echo "BEGIN: config.fax"

    export SENDCOM="YES"

    export TMPDIR=$STMP
    export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc"
    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc"
    export COMOUTwmo="$COMOUT/wmo"

    echo "END: config.fax" 
