# This file is used to generate config.fbwind, which has settings for the GFS fbwind step

config_fbwind:
  filename: config.fbwind
  content: !expand |
    #!/bin/ksh -x
   
    ########## config.fbwind ##########
    # GFS fbwind step specific

    echo "BEGIN: config.fbwind"

    export SENDCOM="YES"

    export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc"
    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc"
    export COMOUTwmo="$COMOUT/wmo"

    echo "END: config.fbwind" 
