config_fv3:
  filename: config.fv3
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.fv3 ##########
    # FV3 model resolution specific parameters
    # e.g. time-step, processor layout, physics and dynamics parameters
    # This config sets default variables for FV3 for a given resolution
    # User can over-ride after sourcing this config file
    
    if [ $# -ne 1 ]; then
    
        echo "Must specify a forecast mdoe to set variables!"
        echo "argument can be any one of the following:"
        echo "EFCS GFS GDAS   (upper- or lower-case is okay)"
        err_exit "Missing mandatory argument to config.fv3"
        exit 1
    
    fi
    
    forecast_mode=$( echo "$1" | tr a-z A-Z )
    
    echo "BEGIN: config.fv3 for $forecast_mode"
    
    case "$forecast_mode" in
        EFCS)
            export DELTIM={doc.fv3_enkf_settings.DELTIM}
            export layout_x={doc.fv3_enkf_settings.layout_x}
            export layout_y={doc.fv3_enkf_settings.layout_y}
            export WRITE_GROUP={doc.fv3_enkf_settings.WRITE_GROUP}
            export WRTTASK_PER_GROUP={doc.fv3_enkf_settings.WRTTASK_PER_GROUP}
            export WRTIOBUF={doc.fv3_enkf_settings.WRTIOBUF}
            export nth_fv3={sched.nodes.omp_threads_for(doc.resources.efcs[0])}
            export npe_node_fcst={sched.nodes.max_ranks_per_node(doc.resources.efcs[0])}
            {f"export cdmbgwd={doc.fv3_enkf_settings.cdmbgwd}"
                if "cdmbgwd" in doc.fv3_enkf_settings
                  else "# not setting cdmbgwd"}
            ;;
        GFS)
            export DELTIM={doc.fv3_gfs_settings.DELTIM}
            export layout_x={doc.fv3_gfs_settings.layout_x}
            export layout_y={doc.fv3_gfs_settings.layout_y}
            export WRITE_GROUP={doc.fv3_gfs_settings.WRITE_GROUP}
            export WRTTASK_PER_GROUP={doc.fv3_gfs_settings.WRTTASK_PER_GROUP}
            export WRTIOBUF={doc.fv3_gfs_settings.WRTIOBUF}
            export nth_fv3={sched.nodes.omp_threads_for(doc.resources.efcs[0])}
            export npe_node_fcst={sched.nodes.max_ranks_per_node(doc.resources.efcs[0])}
            {f"export cdmbgwd={doc.fv3_gfs_settings.cdmbgwd}"
                if "cdmbgwd" in doc.fv3_gfs_settings
                  else "# not setting cdmbgwd"}
            ;;
        GDAS)
            export DELTIM={doc.fv3_gdas_settings.DELTIM}
            export layout_x={doc.fv3_gdas_settings.layout_x}
            export layout_y={doc.fv3_gdas_settings.layout_y}
            export WRITE_GROUP={doc.fv3_gdas_settings.WRITE_GROUP}
            export WRTTASK_PER_GROUP={doc.fv3_gdas_settings.WRTTASK_PER_GROUP}
            export WRTIOBUF={doc.fv3_gdas_settings.WRTIOBUF}
            export nth_fv3={sched.nodes.omp_threads_for(doc.resources.efcs[0])}
            export npe_node_fcst={sched.nodes.max_ranks_per_node(doc.resources.efcs[0])}
            {f"export cdmbgwd={doc.fv3_gdas_settings.cdmbgwd}"
                if "cdmbgwd" in doc.fv3_gdas_settings
                  else "# not setting cdmbgwd"}
            ;;
        *)
            err_exit "Specify GFS, GDAS, or EFCS when calling config.fv3.in"
            exit 2
    esac
    
    echo "END: config.fv3 for $forecast_mode"
    
