# This file is used to generate config.gempak, which has settings for the GFS gempak step

config_gempak:
  filename: config.gempak
  content: !expand |
    #!/bin/ksh -x
   
    ########## config.gempak ##########
    # GFS gempak step specific

    echo "BEGIN: config.gempak"

    # Get task specific resources
    . $EXPDIR/config.resources gempak

    export GEMPAKSH=$HOMEgfs/jobs/JGFS_GEMPAK

    echo "END: config.gempak" 
