# This file is used to generate config.pgrb2_spec_npoess, which has settings for the GFS pgrb2_spec_npoess step

config_pgrb2_spec_npoess:
  filename: config.pgrb2_spec_npoess
  content: !expand |
    #!/bin/ksh -x
   
    ########## config.pgrb2_spec_npoess ##########
    # GFS pgrb2_spec_npoess step specific

    echo "BEGIN: config.pgrb2_spec_npoess"

    export SENDCOM="YES"

    export GEMPAKSH=$HOMEgfs/jobs/JGFS_GEMPAK
    export FIXgfs=$HOMEgfs/gempak/fix
    export USHgfs=$HOMEgfs/gempak/ush
    export FIXgempak=$HOMEgfs/gempak/fix
    export USHgempak=$HOMEgfs/gempak/ush

    export COMIN=$ROTDIR/$RUN.$PDY/$cyc
    export COMOUT=$ROTDIR/$RUN.$PDY/$cyc

    echo "END: config.pgrb2_spec_npoess" 
