# This file is used to generate config.postsnd, which has settings for the GFS postsnd step

config_postsnd:
  filename: config.postsnd
  content: !expand |
    #!/bin/ksh -x
  
    ########## config.postsnd ##########
    # GFS bufr sounding step specific

    echo "BEGIN: config.postsnd"

    # Get task specific resources
    . $EXPDIR/config.resources postsnd

    export POSTSNDSH=$HOMEgfs/jobs/JGFS_POSTSND

    echo "END: config.postsnd" 
