config_prep:
  filename: config.prep
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.prep ##########
    # Prep step specific
    
    echo "BEGIN: config.prep"
    
    # Get task specific resources
    . $EXPDIR/config.resources prep
    
    export DO_MAKEPREPBUFR="{tools.YES_NO(doc.data_assimilation.DO_MAKEPREPBUFR)}"   # if NO, will copy prepbufr from globaldump
    
    
    # Relocation and syndata QC
    export REALTIME="{tools.YES_NO(doc.data_assimilation.PREP_REALTIME)}"
    export PROCESS_TROPCY="{tools.YES_NO(doc.data_assimilation.PROCESS_TROPCY)}"
    if [ $machine = "WCOSS_C" ]; then
        [[ $REALTIME == "YES" || $RUN_ENVIR == "nco" ]] && export PROCESS_TROPCY="YES"
    fi
    export DO_RELOCATE="{tools.YES_NO(doc.data_assimilation.DO_RELOCATE)}"
    export TROPCYQCRELOSH="$HOMEgfs/scripts/extropcy_qc_reloc.sh.ecf"
    export SENDCOM=YES
    
    export HOMERELO=$HOMEgfs
    export EXECRELO=${{HOMERELO}}/exec
    export FIXRELO=${{HOMERELO}}/fix/fix_am
    export USHRELO=${{HOMERELO}}/ush
    
    export HOMESYND=$HOMEgfs
    export EXECSYND=${{HOMESYND}}/exec
    export USHSYND=${{HOMESYND}}/ush
    export PARMSYND=${{HOMESYND}}/parm/relo
    export FIXSYND=${{HOMESYND}}/fix/fix_am
    
    ###################################
    # Only used when DO_RELOCATE=YES
    # ignore them for now
    ###################################
    #export machine=${{machine:-WCOSS_C}}
    #if [ $machine = WCOSS_C ] ; then
    #   export APRNGETTX="time aprun -q -j1 -n1 -N1 -d1 -cc depth"
    #   export APRNRELOC="time aprun -q -j1 -n7 -N1 -d24 -cc depth "
    #   export APRNSYNDX="time aprun -q -j1 -n1 -N1 -d1 -cc depth"
    #fi
    
    
    echo "END: config.prep"
    
