# This file is used to tell the underlying scripts how many threads or
# MPI ranks are used for various executed programs.  Many of the
# programs listed here are for the full workflow, such as analysis or
# ENKF jobs.  Hence, only a few of these are used.  Specifically, the
# ones in the post, fcst, and getic sections of the large "if" block.

config_resources:
  filename: "config.resources"
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.resources ##########
    # Set resource information for job tasks
    # e.g. walltime, node, cores per node, memory etc.
    
    if [ $# -ne 1 ]; then
    
        echo "Must specify an input task argument to set resource variables!"
        echo "argument can be any one of the following:"
        echo "anal fcst post vrfy arch"
        echo "eobs eomg eupd ecen efcs epos earc"
        echo "postsnd awips gempak"
        exit 1
    
    fi
    
    step=$1
    
    echo "BEGIN: config.resources"

    if [[ "$step" == "prep" ]] ; then
        export npe_prep={doc.aliases.prep.npe}
        export npe_node_prep={doc.aliases.prep.npe_node}

    elif [[ "$step" == "prepbufr" ]] ; then
        export npe_prepbufr={doc.aliases.prepbufr.npe}
        export npe_node_prepbufr={doc.aliases.prepbufr.npe_node}

    elif [[ "$step" == "anal" ]] ; then
        export npe_anal={doc.aliases.anal.npe}
        export npe_node_anal={doc.aliases.anal.npe_node}
        export nth_anal={doc.aliases.anal.nth}

    elif [[ "$step" == "fcst" ]] ; then
        if [[ "${{CDUMP:-}}" == gdas ]] ; then
            export npe_fcst={doc.aliases.gdasfcst.npe}
            export npe_node_fcst={doc.aliases.gdasfcst.npe_node}
        else
            export npe_fcst={doc.aliases.gfsfcst.npe}
            export npe_node_fcst={doc.aliases.gfsfcst.npe_node}
        fi

    elif [[ "$step" == "post" ]] ; then
        if [[ "${{CDUMP:-}}" == gdas ]] ; then
            export npe_post={doc.aliases.gdaspost.npe}
            export npe_node_post={doc.aliases.gdaspost.npe_node}
        else
            export npe_post={doc.aliases.gfspost.npe}
            export npe_node_post={doc.aliases.gfspost.npe_node}
        fi

    elif [[ "$step" == "vrfy" ]] ; then
        export npe_vrfy={doc.aliases.gdasvrfy.npe}
        export npe_node_vrfy={doc.aliases.gdasvrfy.npe_node}
        export npe_vrfy_gfs={doc.aliases.gfsvrfy.npe}
        export npe_node_vrfy_gfs={doc.aliases.gfsvrfy.npe_node}

    elif [[ "$step" == "arch" ]] ; then
        export npe_arch={doc.aliases.arch.npe}
        export npe_node_arch={doc.aliases.arch.npe_node}

    elif [[ "$step" == "earc" ]] ; then
        export npe_earc={doc.aliases.earc.npe}
        export npe_node_earc={doc.aliases.earc.npe_node}

    elif [[ "$step" == "getic" ]] ; then
        export npe_getic={doc.aliases.getic.npe}
        export npe_node_getic={doc.aliases.getic.npe_node}

    elif [[ "$step" == "eobs" ]] ; then
        export npe_eobs={doc.aliases.eobs.npe}
        export npe_node_eobs={doc.aliases.eobs.npe_node}

    elif [[ "$step" == "eomg" ]] ; then
        export npe_getic={doc.aliases.eomg.npe}
        export npe_node_eomg={doc.aliases.eomg.npe_node}

    elif [[ "$step" == "eupd" ]] ; then
        export npe_eupd={doc.aliases.eupd.npe}
        export npe_node_eupd={doc.aliases.eupd.npe_node}

    elif [[ "$step" == "ecen" ]] ; then
        export npe_ecen={doc.aliases.ecen.npe}
        export npe_node_ecen={doc.aliases.ecen.npe_node}

    elif [[ "$step" == "efcs" ]] ; then
        export npe_efcs={doc.aliases.efcs.npe}
        export npe_node_efcs={doc.aliases.efcs.npe_node}

    elif [[ "$step" == "epos" ]] ; then
        export npe_epos={doc.aliases.epos.npe}
        export npe_node_epos={doc.aliases.epos.npe_node}

    elif [[ "$step" == "awips" ]] ; then
        export npe_awips={doc.aliases.awips.npe}
        export npe_node_awips={doc.aliases.awips.npe_node}

    elif [[ "$step" == "postsnd" ]] ; then
        export npe_postsnd={doc.aliases.postsnd.npe}
        export npe_node_postsnd={doc.aliases.postsnd.npe_node}
        export npe_postsndcfp={doc.aliases.postsndcfp.npe}
        export npe_node_postsndcfp={doc.aliases.postsndcfp.npe_node}

    elif [[ "$step" == "gempak" ]] ; then
        export npe_gempak={doc.aliases.gempak.npe}
        export npe_node_gempak={doc.aliases.gempak.npe_node}

    else
    
        echo "Invalid step = $step, ABORT!"
        exit 2
    
    fi
    
    echo "END: config.resources"
